# Fichier suricata.yaml généré par docker-build.sh
# Ce fichier sera monté en lecture seule dans le conteneur suricata.

# Pourcentage de paquets à traiter avant d'abandonner
max-pending-packets: 1024

# Configuration de base des variables
vars:
  # Chemin vers les fichiers de règles (relatif à /etc/suricata/ dans le conteneur)
  rule-files:
    - rules/suricata.rules # Assurez-vous que ce fichier existe dans le volume suricata-rules ou l'image

  # Variables d'adresses réseau
  address-groups:
    # Réseau local principal
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"

    # Serveurs externes (pas HOME_NET)
    EXTERNAL_NET: "!$HOME_NET"

    # Serveurs HTTP
    HTTP_SERVERS: "$HOME_NET"

    # Serveurs SMTP
    SMTP_SERVERS: "$HOME_NET"

    # Serveurs DNS
    DNS_SERVERS: "$HOME_NET"

  # Variables de ports
  port-groups:
    # Ports HTTP
    HTTP_PORTS: "80"

    # Ports SSL/TLS
    SSL_PORTS: "443"

    # Ports SMTP
    SMTP_PORTS: "25"

    # Ports DNS
    DNS_PORTS: "53"

# Répertoire par défaut pour les logs (dans le conteneur)
default-log-dir: /var/log/suricata/

# Paramètres de classification (relatif à /etc/suricata/ dans le conteneur)
classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config

# Configuration de la capture de paquets (AF_PACKET) - L'interface est définie par la variable d'env eth0
# af-packet: # Cette section sera gérée dynamiquement par entrypoint.sh si besoin
#   - interface: default

# Configuration des threads et du mode d'exécution
threading:
  # set-cpu-affinity: yes # Commenté par défaut, activer si nécessaire
  runmode: auto

# Activer le socket Unix pour l'API
unix-command:
  enabled: yes
  filename: suricata-command.socket # Sera créé dans /var/run/suricata/ grâce au volume

# Chemin vers le fichier PID
pid-file: /var/run/suricata/suricata.pid # Sera créé dans /var/run/suricata/ grâce au volume

# Configuration des sorties
outputs:
  # Sortie EVE JSON (recommandée pour l'interface web ou autre traitement)
  - eve-log:
      enabled: yes
      type: file
      filename: eve.json
      # Types d'événements à inclure
      types:
        - alert: {payload: yes, payload-buffer-size: 4kb, payload-printable: yes}
        - http: {extended: yes}
        - dns
        - tls: {extended: yes}
        - files: {force-magic: yes, force-hash: [md5,sha1,sha256]}
        - smtp
        - flow
        - netflow
        - stats: {interval: 8} # Stats toutes les 8 secondes
        - anomaly # Inclus les événements d'anomalie
      community-id: true # Activer l'ID de communauté

  # Sortie "fast log" (simple, pour les alertes)
  - fast:
      enabled: yes
      filename: fast.log

  # Sortie "stats.log" (plus détaillée que eve stats)
  - stats:
      enabled: yes
      filename: stats.log
      interval: 8
      totals: yes      # include totals
      threads: yes     # per thread stats
      # Per-protocol stats
      # decoder-events: yes
      # stream-events: yes

  # Sortie "unified2" (format binaire, pour Barnyard2 etc.)
  # - unified2-alert:
  #     enabled: yes
  #     filename: unified2.alert

# Actions en cas d'erreur
# engine-analysis:
  # rules-fast-pattern: yes

# Option pour exécuter en tant qu'utilisateur non-root après démarrage
# run-as:
  # user: suricata
  # group: suricata
