# Fichier suricata.yaml généré par docker-build.sh

# Pourcentage de paquets à traiter avant d'abandonner
max-pending-packets: 1024

# Configuration de base des variables
vars:
  # Chemin vers les fichiers de règles
  rule-files:
    - suricata.rules

  # Variables d'adresses réseau
  address-groups:
    # Réseau local principal
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"

    # Serveurs externes (pas HOME_NET)
    EXTERNAL_NET: "!$HOME_NET"

    # Serveurs HTTP
    HTTP_SERVERS: "$HOME_NET"

    # Serveurs SMTP
    SMTP_SERVERS: "$HOME_NET"

    # Serveurs DNS
    DNS_SERVERS: "$HOME_NET"

  # Variables de ports
  port-groups:
    # Ports HTTP
    HTTP_PORTS: "80"

    # Ports SSL/TLS
    SSL_PORTS: "443"

    # Ports SMTP
    SMTP_PORTS: "25"

    # Ports DNS
    DNS_PORTS: "53"

# Répertoire par défaut pour les logs (sera dans le conteneur)
default-log-dir: /var/log/suricata/

# Paramètres de classification
classification-file: /etc/suricata/classification.config
# Référence pour les métadonnées de règles
reference-config-file: /etc/suricata/reference.config

# Configuration de la capture de paquets (AF_PACKET)
af-packet:
  - interface: eth0@if209
    # cluster-id: 99 # Commenté par défaut, peut être utile si plusieurs instances
    # cluster-type: cluster_flow # Recommandé si cluster-id est utilisé
    # checksum-checks: kernel # Défaut
    # defrag: yes # Recommandé
    # use-mmap: yes # Recommandé
    # tpacket-v3: yes # Recommandé si supporté

# Configuration des threads et du mode d'exécution
threading:
  # set-cpu-affinity: yes # Commenté par défaut, activer si nécessaire
  runmode: auto

# Configuration des sorties
outputs:
  # Sortie EVE JSON (recommandée)
  - eve-log:
      enabled: yes
      type: file
      filename: eve.json
      # Types d'événements à inclure
      types:
        - alert
        - http: {extended: yes} # Infos HTTP étendues
        - dns
        - tls: {extended: yes} # Infos TLS étendues
        - files: {force-magic: yes, force-hash: [md5,sha1,sha256]}
        - smtp
        - flow
        - netflow
        - stats: {interval: 8} # Stats toutes les 8 secondes

  # Sortie "fast log" (simple, pour les alertes)
  - fast:
      enabled: yes
      filename: fast.log

  # Sortie "unified2" (format binaire, pour Barnyard2 etc.)
  # - unified2-alert:
  #     enabled: yes
  #     filename: unified2.alert

# Actions en cas d'erreur
# engine-analysis:
  # rules-fast-pattern: yes

# Option pour exécuter en tant qu'utilisateur non-root après démarrage
# run-as:
  # user: suricata
  # group: suricata

# Chemin vers le fichier PID
pid-file: /var/run/suricata/suricata.pid
